name: ghfeat
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.12.0=py36h06a4308_0
  - astor=0.8.1=py36h06a4308_0
  - blas=1.0=mkl
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.1.19=h06a4308_1
  - certifi=2020.12.5=py36h06a4308_0
  - coverage=5.5=py36h27cfd23_2
  - cudatoolkit=9.2=0
  - cudnn=7.6.5=cuda9.2_0
  - cupti=9.2.148=0
  - cython=0.29.22=py36h2531618_0
  - gast=0.4.0=py_0
  - grpcio=1.36.1=py36h2157cd5_1
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - importlib-metadata=3.7.3=py36h06a4308_1
  - intel-openmp=2020.2=254
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libprotobuf=3.14.0=h8c45485_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markdown=3.3.4=py36h06a4308_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.0.1=py36h06a4308_0
  - protobuf=3.14.0=py36h2531618_1
  - python=3.6.13=hdb3f193_0
  - pyyaml=5.4.1=py36h27cfd23_1
  - readline=8.1=h27cfd23_0
  - scipy=1.5.2=py36h0b6359f_0
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.35.3=hdfb4753_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=gpu_py36he74679b_0
  - tensorflow-base=1.12.0=gpu_py36had579c0_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - termcolor=1.1.0=py36h06a4308_1
  - tk=8.6.10=hbc83047_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - backcall==0.2.0
    - chardet==4.0.0
    - decorator==5.0.0
    - idna==2.10
    - ipdb==0.13.7
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - opencv-python==4.5.1.48
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.2.0
    - prompt-toolkit==3.0.18
    - ptyprocess==0.7.0
    - pygments==2.8.1
    - requests==2.25.1
    - toml==0.10.2
    - tqdm==4.59.0
    - traitlets==4.3.3
    - urllib3==1.26.4
    - wcwidth==0.2.5
